### ISSUE TITLE
error: No compatible binary build found for this package.

### ISSUE THREAD

**Issue by osxi** [jagi/meteor-node-canvas#1]
I'm getting the following error on OSX with Meteor 1.1.0.2

```
$ meteor add jagi:node-canvas
 => Errors while adding packages:

While checking for jagi:node-canvas@0.1.0:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

**Comment by lukejagodzinski** [comment]
I know this, you would have to manually install all dependencies for you platform. When I was making this package I didn't know about publishing to other platforms. I'm busy working on Astronomy package and don't have time to update this one.

**Comment by osxi** [comment]
Hey it's all good and thanks for creating the package. I ended up just using `meteorhacks:npm` to access the node-canvas project.
